title: AI4Space 2022
email: tat-jun.chin@adelaide.edu.au
description: Website for the Workshop on AI for Space at ECCV 2022
  ---
baseurl: "/2024" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']
