title: AI4Space 2024
email: tat-jun.chin@adelaide.edu.au
description: Website for the Workshop on AI for Space at CVPR 2024
  ---
baseurl: "/2024" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']
